---

language: go

go:
  - 1.x

matrix:
  fast_finish: true

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - if [ -n "$TRAVIS_TAG" ]; then sudo apt-get install -y rpm build-essential fakeroot expect debsigs; fi
  - if [ -n "$TRAVIS_TAG" ]; then openssl aes-256-cbc -K $encrypted_6b7e08428daf_key -iv $encrypted_6b7e08428daf_iv -in dist/gpg_key.priv.enc -out dist/gpg_key.priv -d; fi

before_script:
  - golint -set_exit_status ./...
  - go vet ./... | grep ':' && false || true
  - go test -v -cover ./...
  - if [ -n "$TRAVIS_TAG" ]; then go install github.com/jtyr/gbt/cmd/gbt && $GOPATH/bin/gbt -version | egrep " $TRAVIS_TAG\$"; fi

script:
  - go install github.com/jtyr/gbt/cmd/gbt
  - $GOPATH/bin/gbt -version
  - if [ -n "$TRAVIS_TAG" ]; then dist/build.sh; fi
  - for N in $(go list ./...); do go test -v -covermode=count -coverprofile=${N//\//_}.out $N 1>/dev/null; done
  - echo 'mode:'' count' > coverage.out && cat *.out | grep -v 'mode:' | sort -r | awk '{if($1 != last) {print $0;last=$1}}' >> coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  - provider: releases
    api_key:
      secure: T4S4Ea82+QpI0CNHYHZTKRe9L4lJ6TKEb2zsvAwvd8fdmR58L6N+0WhNQ6f6zczBl5ufeAvWlmYdLVCViFMzZVHOYkgT+ehSuT1wTh1sSpPpxATzN9nl53bsDxH1pSL0uht+os7HYXDZDsIr1Kpn6NbFeCJKdXhqb+0HgXyNc+k5jFMNSBkJsCY8aeegr9e6W7l6QvGwaAzqm4MNGgXeIw6uqMf5r0H4OqswudfaQ3/SOz1eTn1GvGNOCYmyM519Jd0hPvvLANzAqwC4M93yVdZm/fahZbY20HvELNbO2mXJUND4ojw/GcXRMjfx1c9TcvhFeBQNZPwHNGPc1ygoKo+BrRf7ZhY2WcwL580mT4yEbvtSbYUFqGNW1J+HiVr2BdYzOLK5jIEuaRrc1ex/BUUvyLGyd2b74NtHATYynG1Bjfu9LwDiVoo5zzpDfCPf00jIH8oC91zS41K7PrlC3kVchijU5wJDQ05dabThxb3RQ5lumrqZYEajG+hpm1+9DEQ3M1jJBSRY/frc8Gr3PTlfrc+INZXrp3vaFFjmISQYuEy1qFpoSTwnBK7eGzFL/B5jfPveJcjpHlINqGGQ3ilv2RLkSRh3ima0xHhtyDmUSF9cT26VrfPfOeytFtMwWHIFToiZtnqFd8VZk3DUyCDsTXWMtF+OMyhipd2MD4s=
    file_glob: true
    file:
      - /tmp/gbt/*.tar.gz
      - /tmp/gbt/*.deb
      - /tmp/gbt/*.rpm
      - /tmp/gbt/*.txt
    skip_cleanup: true
    on:
      tags: true
      repo: jtyr/gbt

  - provider: packagecloud
    username: gbt
    repository: release
    token:
      secure: dqvuV55yoBumwteOf8HcsWraOBP0EaGvbYqEUHZUscL16IEe9Cmf+sfl3UekMUFoOmLchX0vLh2FD4izXlEHHQQDiW2lDVem1bjIgvEsRYPDZ/noFdXNIB7pAlMGhgeQUNGqm6OYVH47xB7RUEZvRPAYZ8whLKE5S/F1NKjRHQzGys92/aks3auNos35xX32KVHnc4eIylYigSHWFtmxKsUh1svlIGQpG1cfXVnjJAHDyxrWj42Ewd7u6Hrh3A4dpbazkMbJhXPx5TGQsfHOiEbaT+8QUq3mcO4QbOkZMdkyv4wBnfuZO+m1F40OfnD9WyVvFEROIiIFZF8KcOrM4JGjoR3SXe3GwWVeZmYbMwo/Y+RB9fHCA0prjhZgikl2e7TwpL5dc1mCyplFrTcwHIfhdQFGZZ7dZ4RQEZBFlw7t8VyIaukSzlZ0LRfcktlRop1+j+X9UJA0lgsMjT4wl5pbd2cGpb4BnBM6H4QdRN3msD1c7wR7VSjCdB3YMNkURQDMyxPjjeRHCaCKqN2u7wC/afAT0FDQLlP3dfdMyiHxHjVLC+JYaAdLYnQl8vhtGVnOEddIUe4VDQYaA5QOsFQEUTLH01jE0qLMgFTWrn2KNDDBwhh8dNcTCaAeOncA0P5qWqKuT1Wtw3DOdprviS0kAlHqTkjlj6Wv17Tsep8=
    dist: ubuntu/xenial
    skip_cleanup: true
    local-dir: /tmp/gbt
    package_glob: "*64.deb"
    on:
      tags: true
      repo: jtyr/gbt

  - provider: packagecloud
    username: gbt
    repository: release
    token:
      secure: dqvuV55yoBumwteOf8HcsWraOBP0EaGvbYqEUHZUscL16IEe9Cmf+sfl3UekMUFoOmLchX0vLh2FD4izXlEHHQQDiW2lDVem1bjIgvEsRYPDZ/noFdXNIB7pAlMGhgeQUNGqm6OYVH47xB7RUEZvRPAYZ8whLKE5S/F1NKjRHQzGys92/aks3auNos35xX32KVHnc4eIylYigSHWFtmxKsUh1svlIGQpG1cfXVnjJAHDyxrWj42Ewd7u6Hrh3A4dpbazkMbJhXPx5TGQsfHOiEbaT+8QUq3mcO4QbOkZMdkyv4wBnfuZO+m1F40OfnD9WyVvFEROIiIFZF8KcOrM4JGjoR3SXe3GwWVeZmYbMwo/Y+RB9fHCA0prjhZgikl2e7TwpL5dc1mCyplFrTcwHIfhdQFGZZ7dZ4RQEZBFlw7t8VyIaukSzlZ0LRfcktlRop1+j+X9UJA0lgsMjT4wl5pbd2cGpb4BnBM6H4QdRN3msD1c7wR7VSjCdB3YMNkURQDMyxPjjeRHCaCKqN2u7wC/afAT0FDQLlP3dfdMyiHxHjVLC+JYaAdLYnQl8vhtGVnOEddIUe4VDQYaA5QOsFQEUTLH01jE0qLMgFTWrn2KNDDBwhh8dNcTCaAeOncA0P5qWqKuT1Wtw3DOdprviS0kAlHqTkjlj6Wv17Tsep8=
    dist: el/7
    skip_cleanup: true
    local-dir: /tmp/gbt
    package_glob: "*.rpm"
    on:
      tags: true
      repo: jtyr/gbt

env:
  global:
    - secure: Am1FJP2T9i/Xb1TNU0mVk39bAU7BXbreR+hgagTAPFWspsZPneFNn7v2XHx62voR/oiaXB/wYQH4+F/+bbTjf+dAFZvEDKzMeWM9zGbNucG4zs2q3NzEJsRVdqWwg8hdM+6Qkokz73eSaxwTsePqVfNntn4Qt0FlNOk0FXPBCuBFIIqvqj4py/ssYDcC7mgsezF/fpJZG9W3py+0tmaxZTssdPENS3PAkqvnDcJuKj3a88oGPEpkmN8D0MTNPJqx/SXd/NCnUFDaeysMr8tuSEapEFoajd1NS3ihL91oEuBN5je6GxezYhiNhx6joxykNwnqDbDzo4isDxjU5CAUigLJkeFieiF8VSNbLj6wifm01tFy0I7IyvtdLBkRNnH999+6jnCPptIasI0FibIRORWWHa6077Y44BhCsqe5eIHtXLAOcDcdn0tHo8TtfnPX9x7zU/gzTqD6mJ65lbXW4TS2Mgv2lPL9vVuz/ad+rRYwwItM9k1ato5O10r5dSzoUaiXgYbsLdex1uIce0MuLiZutQ3FEA2uTaxh1kwKr7gQZuGMkBv5TNrBkLYC2CUiEFSipYnZ5oBSEH4p51QiWqgg82b/LX3AG7p/QYVQuFExSCFmUOTcCZOTCBJxXKiX9mzHWsE2USU/doN4lPL6EX3paCcJKTgI8Z/uyU0+0eA=

notifications:
  email: false
